export const availabilityOptions = [
    { label: "Not Available", value: "none" },
    { label: "Morning", value: "morning" },
    { label: "Afternoon", value: "afternoon" },
    { label: "Full-Day", value: "fullday" },
  ]

export const maritalOptions = [
  { label: "Single", value: "single"},
  { label: "Married", value: "married"},
  { label: "Divorced", value: "divorced"},
  { label: "Widowed", value: "widowed"},
]

export const phoneOptions = [
  { label: "Home", value: "home" },
  { label: "Mobile", value: "mobile" },
  { label: "Work", value: "work" },
  { label: "Other", value: "other" }
]

export const residenceOptions = [
  { label: "Current", value: "current" },
  { label: "Previous", value: "previous" }
]

export const workLengthOptions = [
  { label: "Full-Time", value: "fulltime" },
  { label: "Part-Time", value: "parttime" },
  { label: "Temporary", value: "temporary" },
  { label: "PNR", value: "pnr" }
]

export const workScheduleOptions = [
  { label: "Weekdays", value: "weekdays" },
  { label: "Weekends", value: "weekends" },
  { label: "Evenings", value: "evenings" },
  { label: "Overtime", value: "overtime" },
  { label: "Other", value: "other" }
]

export const referenceOptions = [
  { label: "Professional", value: "professional" },
  { label: "Personal", value: "personal" }
]

export const referralSourceOptions = [
  { label: "Hospital", value: "hospital" },
  { label: "Employee", value: "employee" },
  { label: "Volunteer Event", value: "volunteer" },
  { label: "Patient", value: "patient" },
  { label: "Facebook", value: "facebook" },
  { label: "Google", value: "google" },
  { label: "Other", value: "other" }
]

// Boolean
export const consentOptions = [
  { label: "Do not consent", value: "no" },
  { label: "Consent", value: "yes" },
]

export const haveOptions = [
  { label: "have not", value: "no" },
  { label: "have", value: "yes" },
]

export const agreeOptions = [
  { label: "Disagree", value: "no" },
  { label: "Agree", value: "yes" },
]

export const acceptOptions = [
  { label: "I Don't Accept", value: "no" },
  { label: "I Accept", value: "yes" },
]

export const signitureOptions = [
  { label: "Do not Sign", value: "no" },
  { label: "Sign", value: "yes" },
]

export const yesOptions = [
  {label: "No", value: "no"}, 
  {label: "Yes", value: "yes"}
]



export const usStateOptions = [
  { label: "Armed Forces (AA)", value: "AA" },
  { label: "Armed Forces (AE)", value: "AE" },
  { label: "Armed Forces (AP)", value: "AP" },
  { label: "Alabama", value: "AL" },
  { label: "Alaska", value: "AK" },
  { label: "American Samoa", value: "AS" },
  { label: "Arizona", value: "AZ" },
  { label: "Arkansas", value: "AR" },
  { label: "Colorado", value: "CO" },
  { label: "Connecticut", value: "CT" },
  { label: "Delaware", value: "DE" },
  { label: "District Of Columbia", value: "DC" },
  { label: "Federated States of Micronesia", value: "FM" },
  { label: "Florida", value: "FL" },
  { label: "Georgia", value: "GA" },
  { label: "Guam", value: "GU" },
  { label: "Hawaii", value: "HI" },
  { label: "Idaho", value: "ID" },
  { label: "Illinois", value: "IL" },
  { label: "Indiana", value: "IN" },
  { label: "Iowa", value: "IA" },
  { label: "Kansas", value: "KS" },
  { label: "Kentucky", value: "KY" },
  { label: "Louisiana", value: "LA" },
  { label: "Maine", value: "ME" },
  { label: "Marshall Islands", value: "MH" },
  { label: "Maryland", value: "MD" },
  { label: "Massachusetts", value: "MA" },
  { label: "Michigan", value: "MI" },
  { label: "Minnesota", value: "MN" },
  { label: "Mississippi", value: "MS" },
  { label: "Missouri", value: "MO" },
  { label: "Montana", value: "MT" },
  { label: "Nebraska", value: "NE" },
  { label: "Nevada", value: "NV" },
  { label: "New Hampshire", value: "NH" },
  { label: "New Jersey", value: "NJ" },
  { label: "New Mexico", value: "NM" },
  { label: "New York", value: "NY" },
  { label: "North Carolina", value: "NC" },
  { label: "North Dakota", value: "ND" },
  { label: "Northern Mariana Islands", value: "MP" },
  { label: "Ohio", value: "OH" },
  { label: "Oklahoma", value: "OK" },
  { label: "Oregon", value: "OR" },
  { label: "Palau", value: "PW" },
  { label: "Pennsylvania", value: "PA" },
  { label: "Puerto Rico", value: "PR" },
  { label: "Rhode Island", value: "RI" },
  { label: "South Carolina", value: "SC" },
  { label: "South Dakota", value: "SD" },
  { label: "Tennessee", value: "TN" },
  { label: "Texas", value: "TX" },
  { label: "Utah", value: "UT" },
  { label: "Vermont", value: "VT" },
  { label: "Virgin Islands", value: "VI" },
  { label: "Virginia", value: "VA" },
  { label: "Washington", value: "WA" },
  { label: "West Virginia", value: "WV" },
  { label: "Wisconsin", value: "WI" },
  { label: "Wyoming", value: "WY" }
];

export const usCityOptions = [
	{ label: "Aberdeen", value: "Aberdeen" },
	{ label: "Abilene", value: "Abilene" },
	{ label: "Akron", value: "Akron" },
	{ label: "Albany", value: "Albany" },
	{ label: "Albuquerque", value: "Albuquerque" },
	{ label: "Alexandria", value: "Alexandria" },
	{ label: "Allentown", value: "Allentown" },
	{ label: "Amarillo", value: "Amarillo" },
	{ label: "Anaheim", value: "Anaheim" },
	{ label: "Anchorage", value: "Anchorage" },
	{ label: "Ann Arbor", value: "Ann Arbor" },
	{ label: "Antioch", value: "Antioch" },
	{ label: "Apple Valley", value: "Apple Valley" },
	{ label: "Appleton", value: "Appleton" },
	{ label: "Arlington", value: "Arlington" },
	{ label: "Arvada", value: "Arvada" },
	{ label: "Asheville", value: "Asheville" },
	{ label: "Athens", value: "Athens" },
	{ label: "Atlanta", value: "Atlanta" },
	{ label: "Atlantic City", value: "Atlantic City" },
	{ label: "Augusta", value: "Augusta" },
	{ label: "Aurora", value: "Aurora" },
	{ label: "Austin", value: "Austin" },
	{ label: "Bakersfield", value: "Bakersfield" },
	{ label: "Baltimore", value: "Baltimore" },
	{ label: "Barnstable", value: "Barnstable" },
	{ label: "Baton Rouge", value: "Baton Rouge" },
	{ label: "Beaumont", value: "Beaumont" },
	{ label: "Bel Air", value: "Bel Air" },
	{ label: "Bellevue", value: "Bellevue" },
	{ label: "Berkeley", value: "Berkeley" },
	{ label: "Bethlehem", value: "Bethlehem" },
	{ label: "Billings", value: "Billings" },
	{ label: "Birmingham", value: "Birmingham" },
	{ label: "Bloomington", value: "Bloomington" },
	{ label: "Boise", value: "Boise" },
	{ label: "Boise City", value: "Boise City" },
	{ label: "Bonita Springs", value: "Bonita Springs" },
	{ label: "Boston", value: "Boston" },
	{ label: "Boulder", value: "Boulder" },
	{ label: "Bradenton", value: "Bradenton" },
	{ label: "Bremerton", value: "Bremerton" },
	{ label: "Bridgeport", value: "Bridgeport" },
	{ label: "Brighton", value: "Brighton" },
	{ label: "Brownsville", value: "Brownsville" },
	{ label: "Bryan", value: "Bryan" },
	{ label: "Buffalo", value: "Buffalo" },
	{ label: "Burbank", value: "Burbank" },
	{ label: "Burlington", value: "Burlington" },
	{ label: "Cambridge", value: "Cambridge" },
	{ label: "Canton", value: "Canton" },
	{ label: "Cape Coral", value: "Cape Coral" },
	{ label: "Carrollton", value: "Carrollton" },
	{ label: "Cary", value: "Cary" },
	{ label: "Cathedral City", value: "Cathedral City" },
	{ label: "Cedar Rapids", value: "Cedar Rapids" },
	{ label: "Champaign", value: "Champaign" },
	{ label: "Chandler", value: "Chandler" },
	{ label: "Charleston", value: "Charleston" },
	{ label: "Charlotte", value: "Charlotte" },
	{ label: "Chattanooga", value: "Chattanooga" },
	{ label: "Chesapeake", value: "Chesapeake" },
	{ label: "Chicago", value: "Chicago" },
	{ label: "Chula Vista", value: "Chula Vista" },
	{ label: "Cincinnati", value: "Cincinnati" },
	{ label: "Clarke County", value: "Clarke County" },
	{ label: "Clarksville", value: "Clarksville" },
	{ label: "Clearwater", value: "Clearwater" },
	{ label: "Cleveland", value: "Cleveland" },
	{ label: "College Station", value: "College Station" },
	{ label: "Colorado Springs", value: "Colorado Springs" },
	{ label: "Columbia", value: "Columbia" },
	{ label: "Columbus", value: "Columbus" },
	{ label: "Concord", value: "Concord" },
	{ label: "Coral Springs", value: "Coral Springs" },
	{ label: "Corona", value: "Corona" },
	{ label: "Corpus Christi", value: "Corpus Christi" },
	{ label: "Costa Mesa", value: "Costa Mesa" },
	{ label: "Dallas", value: "Dallas" },
	{ label: "Daly City", value: "Daly City" },
	{ label: "Danbury", value: "Danbury" },
	{ label: "Davenport", value: "Davenport" },
	{ label: "Davidson County", value: "Davidson County" },
	{ label: "Dayton", value: "Dayton" },
	{ label: "Daytona Beach", value: "Daytona Beach" },
	{ label: "Deltona", value: "Deltona" },
	{ label: "Denton", value: "Denton" },
	{ label: "Denver", value: "Denver" },
	{ label: "Des Moines", value: "Des Moines" },
	{ label: "Detroit", value: "Detroit" },
	{ label: "Downey", value: "Downey" },
	{ label: "Duluth", value: "Duluth" },
	{ label: "Durham", value: "Durham" },
	{ label: "El Monte", value: "El Monte" },
	{ label: "El Paso", value: "El Paso" },
	{ label: "Elizabeth", value: "Elizabeth" },
	{ label: "Elk Grove", value: "Elk Grove" },
	{ label: "Elkhart", value: "Elkhart" },
	{ label: "Erie", value: "Erie" },
	{ label: "Escondido", value: "Escondido" },
	{ label: "Eugene", value: "Eugene" },
	{ label: "Evansville", value: "Evansville" },
	{ label: "Fairfield", value: "Fairfield" },
	{ label: "Fargo", value: "Fargo" },
	{ label: "Fayetteville", value: "Fayetteville" },
	{ label: "Fitchburg", value: "Fitchburg" },
	{ label: "Flint", value: "Flint" },
	{ label: "Fontana", value: "Fontana" },
	{ label: "Fort Collins", value: "Fort Collins" },
	{ label: "Fort Lauderdale", value: "Fort Lauderdale" },
	{ label: "Fort Smith", value: "Fort Smith" },
	{ label: "Fort Walton Beach", value: "Fort Walton Beach" },
	{ label: "Fort Wayne", value: "Fort Wayne" },
	{ label: "Fort Worth", value: "Fort Worth" },
	{ label: "Frederick", value: "Frederick" },
	{ label: "Fremont", value: "Fremont" },
	{ label: "Fresno", value: "Fresno" },
	{ label: "Fullerton", value: "Fullerton" },
	{ label: "Gainesville", value: "Gainesville" },
	{ label: "Garden Grove", value: "Garden Grove" },
	{ label: "Garland", value: "Garland" },
	{ label: "Gastonia", value: "Gastonia" },
	{ label: "Gilbert", value: "Gilbert" },
	{ label: "Glendale", value: "Glendale" },
	{ label: "Grand Prairie", value: "Grand Prairie" },
	{ label: "Grand Rapids", value: "Grand Rapids" },
	{ label: "Grayslake", value: "Grayslake" },
	{ label: "Green Bay", value: "Green Bay" },
	{ label: "GreenBay", value: "GreenBay" },
	{ label: "Greensboro", value: "Greensboro" },
	{ label: "Greenville", value: "Greenville" },
	{ label: "Gulfport-Biloxi", value: "Gulfport-Biloxi" },
	{ label: "Hagerstown", value: "Hagerstown" },
	{ label: "Hampton", value: "Hampton" },
	{ label: "Harlingen", value: "Harlingen" },
	{ label: "Harrisburg", value: "Harrisburg" },
	{ label: "Hartford", value: "Hartford" },
	{ label: "Havre de Grace", value: "Havre de Grace" },
	{ label: "Hayward", value: "Hayward" },
	{ label: "Hemet", value: "Hemet" },
	{ label: "Henderson", value: "Henderson" },
	{ label: "Hesperia", value: "Hesperia" },
	{ label: "Hialeah", value: "Hialeah" },
	{ label: "Hickory", value: "Hickory" },
	{ label: "High Point", value: "High Point" },
	{ label: "Hollywood", value: "Hollywood" },
	{ label: "Honolulu", value: "Honolulu" },
	{ label: "Houma", value: "Houma" },
	{ label: "Houston", value: "Houston" },
	{ label: "Howell", value: "Howell" },
	{ label: "Huntington", value: "Huntington" },
	{ label: "Huntington Beach", value: "Huntington Beach" },
	{ label: "Huntsville", value: "Huntsville" },
	{ label: "Independence", value: "Independence" },
	{ label: "Indianapolis", value: "Indianapolis" },
	{ label: "Inglewood", value: "Inglewood" },
	{ label: "Irvine", value: "Irvine" },
	{ label: "Irving", value: "Irving" },
	{ label: "Jackson", value: "Jackson" },
	{ label: "Jacksonville", value: "Jacksonville" },
	{ label: "Jefferson", value: "Jefferson" },
	{ label: "Jersey City", value: "Jersey City" },
	{ label: "Johnson City", value: "Johnson City" },
	{ label: "Joliet", value: "Joliet" },
	{ label: "Kailua", value: "Kailua" },
	{ label: "Kalamazoo", value: "Kalamazoo" },
	{ label: "Kaneohe", value: "Kaneohe" },
	{ label: "Kansas City", value: "Kansas City" },
	{ label: "Kennewick", value: "Kennewick" },
	{ label: "Kenosha", value: "Kenosha" },
	{ label: "Killeen", value: "Killeen" },
	{ label: "Kissimmee", value: "Kissimmee" },
	{ label: "Knoxville", value: "Knoxville" },
	{ label: "Lacey", value: "Lacey" },
	{ label: "Lafayette", value: "Lafayette" },
	{ label: "Lake Charles", value: "Lake Charles" },
	{ label: "Lakeland", value: "Lakeland" },
	{ label: "Lakewood", value: "Lakewood" },
	{ label: "Lancaster", value: "Lancaster" },
	{ label: "Lansing", value: "Lansing" },
	{ label: "Laredo", value: "Laredo" },
	{ label: "Las Cruces", value: "Las Cruces" },
	{ label: "Las Vegas", value: "Las Vegas" },
	{ label: "Layton", value: "Layton" },
	{ label: "Leominster", value: "Leominster" },
	{ label: "Lewisville", value: "Lewisville" },
	{ label: "Lexington", value: "Lexington" },
	{ label: "Lincoln", value: "Lincoln" },
	{ label: "Little Rock", value: "Little Rock" },
	{ label: "Long Beach", value: "Long Beach" },
	{ label: "Lorain", value: "Lorain" },
	{ label: "Los Angeles", value: "Los Angeles" },
	{ label: "Louisville", value: "Louisville" },
	{ label: "Lowell", value: "Lowell" },
	{ label: "Lubbock", value: "Lubbock" },
	{ label: "Macon", value: "Macon" },
	{ label: "Madison", value: "Madison" },
	{ label: "Manchester", value: "Manchester" },
	{ label: "Marina", value: "Marina" },
	{ label: "Marysville", value: "Marysville" },
	{ label: "McAllen", value: "McAllen" },
	{ label: "McHenry", value: "McHenry" },
	{ label: "Medford", value: "Medford" },
	{ label: "Melbourne", value: "Melbourne" },
	{ label: "Memphis", value: "Memphis" },
	{ label: "Merced", value: "Merced" },
	{ label: "Mesa", value: "Mesa" },
	{ label: "Mesquite", value: "Mesquite" },
	{ label: "Miami", value: "Miami" },
	{ label: "Milwaukee", value: "Milwaukee" },
	{ label: "Minneapolis", value: "Minneapolis" },
	{ label: "Miramar", value: "Miramar" },
	{ label: "Mission Viejo", value: "Mission Viejo" },
	{ label: "Mobile", value: "Mobile" },
	{ label: "Modesto", value: "Modesto" },
	{ label: "Monroe", value: "Monroe" },
	{ label: "Monterey", value: "Monterey" },
	{ label: "Montgomery", value: "Montgomery" },
	{ label: "Moreno Valley", value: "Moreno Valley" },
	{ label: "Murfreesboro", value: "Murfreesboro" },
	{ label: "Murrieta", value: "Murrieta" },
	{ label: "Muskegon", value: "Muskegon" },
	{ label: "Myrtle Beach", value: "Myrtle Beach" },
	{ label: "Naperville", value: "Naperville" },
	{ label: "Naples", value: "Naples" },
	{ label: "Nashua", value: "Nashua" },
	{ label: "Nashville", value: "Nashville" },
	{ label: "New Bedford", value: "New Bedford" },
	{ label: "New Haven", value: "New Haven" },
	{ label: "New London", value: "New London" },
	{ label: "New Orleans", value: "New Orleans" },
	{ label: "New York", value: "New York" },
	{ label: "New York City", value: "New York City" },
	{ label: "Newark", value: "Newark" },
	{ label: "Newburgh", value: "Newburgh" },
	{ label: "Newport News", value: "Newport News" },
	{ label: "Norfolk", value: "Norfolk" },
	{ label: "Normal", value: "Normal" },
	{ label: "Norman", value: "Norman" },
	{ label: "North Charleston", value: "North Charleston" },
	{ label: "North Las Vegas", value: "North Las Vegas" },
	{ label: "North Port", value: "North Port" },
	{ label: "Norwalk", value: "Norwalk" },
	{ label: "Norwich", value: "Norwich" },
	{ label: "Oakland", value: "Oakland" },
	{ label: "Ocala", value: "Ocala" },
	{ label: "Oceanside", value: "Oceanside" },
	{ label: "Odessa", value: "Odessa" },
	{ label: "Ogden", value: "Ogden" },
	{ label: "Oklahoma City", value: "Oklahoma City" },
	{ label: "Olathe", value: "Olathe" },
	{ label: "Olympia", value: "Olympia" },
	{ label: "Omaha", value: "Omaha" },
	{ label: "Ontario", value: "Ontario" },
	{ label: "Orange", value: "Orange" },
	{ label: "Orem", value: "Orem" },
	{ label: "Orlando", value: "Orlando" },
	{ label: "Overland Park", value: "Overland Park" },
	{ label: "Oxnard", value: "Oxnard" },
	{ label: "Palm Bay", value: "Palm Bay" },
	{ label: "Palm Springs", value: "Palm Springs" },
	{ label: "Palmdale", value: "Palmdale" },
	{ label: "Panama City", value: "Panama City" },
	{ label: "Pasadena", value: "Pasadena" },
	{ label: "Paterson", value: "Paterson" },
	{ label: "Pembroke Pines", value: "Pembroke Pines" },
	{ label: "Pensacola", value: "Pensacola" },
	{ label: "Peoria", value: "Peoria" },
	{ label: "Philadelphia", value: "Philadelphia" },
	{ label: "Phoenix", value: "Phoenix" },
	{ label: "Pittsburgh", value: "Pittsburgh" },
	{ label: "Plano", value: "Plano" },
	{ label: "Pomona", value: "Pomona" },
	{ label: "Pompano Beach", value: "Pompano Beach" },
	{ label: "Port Arthur", value: "Port Arthur" },
	{ label: "Port Orange", value: "Port Orange" },
	{ label: "Port Saint Lucie", value: "Port Saint Lucie" },
	{ label: "Port St. Lucie", value: "Port St. Lucie" },
	{ label: "Portland", value: "Portland" },
	{ label: "Portsmouth", value: "Portsmouth" },
	{ label: "Poughkeepsie", value: "Poughkeepsie" },
	{ label: "Providence", value: "Providence" },
	{ label: "Provo", value: "Provo" },
	{ label: "Pueblo", value: "Pueblo" },
	{ label: "Punta Gorda", value: "Punta Gorda" },
	{ label: "Racine", value: "Racine" },
	{ label: "Raleigh", value: "Raleigh" },
	{ label: "Rancho Cucamonga", value: "Rancho Cucamonga" },
	{ label: "Reading", value: "Reading" },
	{ label: "Redding", value: "Redding" },
	{ label: "Reno", value: "Reno" },
	{ label: "Richland", value: "Richland" },
	{ label: "Richmond", value: "Richmond" },
	{ label: "Richmond County", value: "Richmond County" },
	{ label: "Riverside", value: "Riverside" },
	{ label: "Roanoke", value: "Roanoke" },
	{ label: "Rochester", value: "Rochester" },
	{ label: "Rockford", value: "Rockford" },
	{ label: "Roseville", value: "Roseville" },
	{ label: "Round Lake Beach", value: "Round Lake Beach" },
	{ label: "Sacramento", value: "Sacramento" },
	{ label: "Saginaw", value: "Saginaw" },
	{ label: "Saint Louis", value: "Saint Louis" },
	{ label: "Saint Paul", value: "Saint Paul" },
	{ label: "Saint Petersburg", value: "Saint Petersburg" },
	{ label: "Salem", value: "Salem" },
	{ label: "Salinas", value: "Salinas" },
	{ label: "Salt Lake City", value: "Salt Lake City" },
	{ label: "San Antonio", value: "San Antonio" },
	{ label: "San Bernardino", value: "San Bernardino" },
	{ label: "San Buenaventura", value: "San Buenaventura" },
	{ label: "San Diego", value: "San Diego" },
	{ label: "San Francisco", value: "San Francisco" },
	{ label: "San Jose", value: "San Jose" },
	{ label: "Santa Ana", value: "Santa Ana" },
	{ label: "Santa Barbara", value: "Santa Barbara" },
	{ label: "Santa Clara", value: "Santa Clara" },
	{ label: "Santa Clarita", value: "Santa Clarita" },
	{ label: "Santa Cruz", value: "Santa Cruz" },
	{ label: "Santa Maria", value: "Santa Maria" },
	{ label: "Santa Rosa", value: "Santa Rosa" },
	{ label: "Sarasota", value: "Sarasota" },
	{ label: "Savannah", value: "Savannah" },
	{ label: "Scottsdale", value: "Scottsdale" },
	{ label: "Scranton", value: "Scranton" },
	{ label: "Seaside", value: "Seaside" },
	{ label: "Seattle", value: "Seattle" },
	{ label: "Sebastian", value: "Sebastian" },
	{ label: "Shreveport", value: "Shreveport" },
	{ label: "Simi Valley", value: "Simi Valley" },
	{ label: "Sioux City", value: "Sioux City" },
	{ label: "Sioux Falls", value: "Sioux Falls" },
	{ label: "South Bend", value: "South Bend" },
	{ label: "South Lyon", value: "South Lyon" },
	{ label: "Spartanburg", value: "Spartanburg" },
	{ label: "Spokane", value: "Spokane" },
	{ label: "Springdale", value: "Springdale" },
	{ label: "Springfield", value: "Springfield" },
	{ label: "St. Louis", value: "St. Louis" },
	{ label: "St. Paul", value: "St. Paul" },
	{ label: "St. Petersburg", value: "St. Petersburg" },
	{ label: "Stamford", value: "Stamford" },
	{ label: "Sterling Heights", value: "Sterling Heights" },
	{ label: "Stockton", value: "Stockton" },
	{ label: "Sunnyvale", value: "Sunnyvale" },
	{ label: "Syracuse", value: "Syracuse" },
	{ label: "Tacoma", value: "Tacoma" },
	{ label: "Tallahassee", value: "Tallahassee" },
	{ label: "Tampa", value: "Tampa" },
	{ label: "Temecula", value: "Temecula" },
	{ label: "Tempe", value: "Tempe" },
	{ label: "Thornton", value: "Thornton" },
	{ label: "Thousand Oaks", value: "Thousand Oaks" },
	{ label: "Toledo", value: "Toledo" },
	{ label: "Topeka", value: "Topeka" },
	{ label: "Torrance", value: "Torrance" },
	{ label: "Trenton", value: "Trenton" },
	{ label: "Tucson", value: "Tucson" },
	{ label: "Tulsa", value: "Tulsa" },
	{ label: "Tuscaloosa", value: "Tuscaloosa" },
	{ label: "Tyler", value: "Tyler" },
	{ label: "Utica", value: "Utica" },
	{ label: "Vallejo", value: "Vallejo" },
	{ label: "Vancouver", value: "Vancouver" },
	{ label: "Vero Beach", value: "Vero Beach" },
	{ label: "Victorville", value: "Victorville" },
	{ label: "Virginia Beach", value: "Virginia Beach" },
	{ label: "Visalia", value: "Visalia" },
	{ label: "Waco", value: "Waco" },
	{ label: "Warren", value: "Warren" },
	{ label: "Washington", value: "Washington" },
	{ label: "Waterbury", value: "Waterbury" },
	{ label: "Waterloo", value: "Waterloo" },
	{ label: "West Covina", value: "West Covina" },
	{ label: "West Valley City", value: "West Valley City" },
	{ label: "Westminster", value: "Westminster" },
	{ label: "Wichita", value: "Wichita" },
	{ label: "Wilmington", value: "Wilmington" },
	{ label: "Winston", value: "Winston" },
	{ label: "Winter Haven", value: "Winter Haven" },
	{ label: "Worcester", value: "Worcester" },
	{ label: "Yakima", value: "Yakima" },
	{ label: "Yonkers", value: "Yonkers" },
	{ label: "York", value: "York" },
	{ label: "Youngstown", value: "Youngstown" },
];